### ISSUE TITLE
Option to suppress displaying value of initiation in REPL?

### ISSUE THREAD

**Issue by bojeryd91** [cormullion/TickTock.jl#3]
Hi,
When I run tick() I always get the "[ Info:  started timer ..." in the console which screws up my other nicely printed info from running a numerical solver I've implemented.

Ending tick() with a semicolon does not suppress the printout. Would that be possible to add as a feature?

P.S. This is the first time I file an issue on someone else's code on Github. I'd be happy to try to make a contribution, but I'm a newbie at this D.S.

**Comment by cormullion** [comment]
Hi! Nice to know that someone uses this code... :) 

It's a good point... `@info`is not the return value of the function, so you can't suppress it with `;`.  But if someone changed line 32 of TickTock.jl from 

```
@info " started timer at: $(now())"
```

to 

```
return " started timer at: $(now())"
```

then you _could_ suppress the return value with a `;`.

Are there other places where this could/should be done?

**Comment by cormullion** [comment]
Another way to do this would be to use environment variables.

So if someone were to change code to this:

```
function __init__()
    if ! haskey(ENV, "TICKTOCK_MESSAGES")
         ENV["TICKTOCK_MESSAGES"] = true
    end
end

function tick()
    t0 = time_ns()
    task_local_storage(:TIMERS, (t0, get(task_local_storage(), :TIMERS, ())))
    if ENV["TICKTOCK_MESSAGES"] == "true"
        @info " started timer at: $(now())"
    end
    return " started timer at: $(now())"
end
```

then you'd be able to switch messages on and off:

```
julia> using TickTock

julia> tick()
[ Info:  started timer at: 2021-04-20T08:58:23.457
" started timer at: 2021-04-20T08:58:23.801"

julia> ENV["TICKTOCK_MESSAGES"] = false
false

julia> tick()
" started timer at: 2021-04-20T08:58:31.259"

julia>
```
